import "./globals.css";
import "../style/index.scss";
import "react-toastify/dist/ReactToastify.css";
import { childrenType } from "@/interFace/interFace";
import ClientProviders from "./ClientProvider";

export default function RootLayout({ children }: childrenType) {
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <title>Book My Stage</title>
          <link rel="icon" href="/favicon.png" />
          <link
            href="https://fonts.googleapis.com/css2?family=Jost:wght@400;500;600;700;900&display=swap"
            rel="stylesheet"
          ></link>
        </head>

        <body suppressHydrationWarning={true}>
          <ClientProviders>{ children }</ClientProviders>
        </body>
      </html>
    </>
  );
}
